INSERT INTO COSMOSDROG.dbo.DROGATEL_INI
(DRIN_TX_ENTRADA, DRIN_TX_VALOR, DRIN_TX_OBSERVACAO, XXXX_DH_ALT, XXXX_CD_USUALT, XXXX_CT_LOCK)
VALUES('APPARAUJO_COM_BR', 'https://hml.apparaujo.araujo.com.br', 'Endereço do hostname da aplicação', '2017-07-05 14:57:59.270', 1, 1);

