package com.clique.retire.enums;

import lombok.Getter;

public enum ParametroEnum {

	QUANTIDADE_IMPRESSAO_TUTORIAL("QUANTIDADE_IMPRESSOES_QUE_MOSTRAM_TUTORIAL"),
	URL_WSDL_SIAC("URL_WSDL_SIAC"),
	TIMEOUT_CONECT_SIAC("TIMEOUT_CONECT_SIAC"),
	TIMEOUT_READ_SIAC("TIMEOUT_READ_SIAC"),
	SERVIDOR_IMPRESSAO_DROGATEL("SERVIDOR_IMPRESSAO_DROGATEL"),
	URL_SERVICO_IMAGENS("URL_SERVICO_IMAGENS"),
	URL_BASE_SERVICOS_REST_DRGT_WEB("URL_BASE_SERVICOS_REST_DRGT_WEB"),
	URL_BASE_CLIQUE_RETIRE_SCHEDULE("URL_BASE_CLIQUE_RETIRE_SCHEDULE"),
	URL_WSDL_SENF_VALIDACAO_USUARIO("URL_WSDL_SENF_VALIDACAO_USUARIO"),
	URL_REST_API_IMPRESSAO_ARAUJO("URL_REST_API_IMPRESSAO_ARAUJO"),
	URL_BASE_BUSCAR_PEDIDO_DROGATEL_POR_PIN("URL_BASE_BUSCAR_PEDIDO_DROGATEL_POR_PIN"),
	URL_BASE_BUSCAR_PEDIDO_PRODUTO_UZ("URL_BASE_BUSCAR_PEDIDO_PRODUTO_UZ"),
	URL_BASE_CARRINHO("URL_BASE_CARRINHO"),	
	URL_SERVIDOR_MAPAS("URL_SERVIDOR_MAPAS"),
	URL_WS_CONVENIO_DROGATEL("URL_WS_CONVENIO_DROGATEL"),
	APPARAUJO_COM_BR("APPARAUJO_COM_BR"),
	PRAZO_PROCESSAMENTO_PEDIDO("PRAZO_PROCESSAMENTO_PEDIDO"),
	AVALIACAO("AVALIACAO"),
	LOJAS_HABILITADO_NOTA_FISCAL("LOJAS_HABILITADO_NOTA_FISCAL"),
	TEMPO_PEDIDO_ATRASADO("TEMPO_PEDIDO_ATRASADO"),
	CODIGO_MOTIVO_DROGATEL_PEDIDO_NAO_ENTREGUE("CODIGO_MOTIVO_DROGATEL_PEDIDO_NAO_ENTREGUE"),
	APLICATIVOS_INTERNOS_URL_BASE_IMAGENS("APLICATIVOS_INTERNOS_URL_BASE_IMAGENS"),
	CLIQUE_RETIRE_CRONOMETRO("CLIQUE_RETIRE_CRONOMETRO"),
	CLIQUE_RETIRE_CRONOMETRO_FUNCIONALIDADES_BLOQUEADAS("CLIQUE_RETIRE_CRONOMETRO_FUNCIONALIDADES_BLOQUEADAS"),
	CLIQUE_RETIRE_PERIODO_INDISPONIBILIDADE_USUARIOS("CLIQUE_RETIRE_PERIODO_INDISPONIBILIDADE_USUARIOS"),
	CLIQUE_RETIRE_PERIODO_INDISPONIBILIDADE_FILTRO("CLIQUE_RETIRE_PERIODO_INDISPONIBILIDADE_FILTRO"),
	URL_BASE_SERVICO_ARMARIO("URL_BASE_SERVICO_ARMARIO"),
	CANAIS_VENDA_SERVICO_ARMARIO("CANAIS_VENDA_SERVICO_ARMARIO"),
	CLIQUE_RETIRE_QUANTIDADE_RETENTATIVAS_PBM("CLIQUE_RETIRE_QUANTIDADE_RETENTATIVAS_PBM"),
	CLIQUE_RETIRE_VERSAO_PAINEL("CLIQUE_RETIRE_VERSAO_PAINEL"),
	URL_BASE_DANFE_PRINTER("URL_BASE_DANFE_PRINTER"),
	IFOOD_PIN_TAMANHO("IFOOD_PIN_TAMANHO"),
	ENDPOINT_CANCELAMENTO_PEDIDO("ENDPOINT_CANCELAMENTO_PEDIDO"),
	ENDPOINT_MOVIMENTACAO_PEDIDO_ECOMMERCE("ENDPOINT_MOVIMENTACAO_PEDIDO_ECOMMERCE"),
	ENDPOINT_CRIAR_PEDIDO_SERVICO("ENDPOINT_CRIAR_PEDIDO_SERVICO"),
	ENDPOINT_ZERO_BALCAO("ENDPOINT_ZERO_BALCAO"),
	PARAMETRO_QUANTIDADE_MAXIMA_PULOS_PARA_TRANSFERENCIA("PARAMETRO_QUANTIDADE_MAXIMA_PULOS_PARA_TRANSFERENCIA"),
	PEDIDO_PENDENTE_FINALIZACAO("PEDIDO_PENDENTE_FINALIZACAO"),
	PERMITE_EDICAO_CONVENIO_MARKETPLACE("PERMITE_EDICAO_CONVENIO_MARKETPLACE");

	@Getter
	private final String descricao;

	ParametroEnum(String descricao) {
        this.descricao = descricao;
	}

}
